In [1]:
import pandas as pd

In [2]:
test = pd.read_csv('Table 3.csv')
test

       x           y  Delta Y (test func)  No. of ideal func
0   12.6  257.215420           -88.455420                  3
1  -14.9    0.267808             0.455074                  2
2   -4.5    6.118259            -1.093322                  0
3    2.4    5.181103            -0.043371                  1
4  -17.9   -0.845322             0.032164                  2
..   ...         ...                  ...                ...
95   7.3   14.125660             0.899558                  1
96 -10.0  -25.212278             5.484288                  1
97 -19.4   -0.169160             0.692225                  2
98  11.0   22.082275            -0.582269                  1
99  10.4  117.566230             0.593770                  3

[100 rows x 4 columns]

In [3]:
test_sort = test.sort_values(['x'], ascending = True)
test_sort

       x           y  Delta Y (test func)  No. of ideal func
97 -19.4   -0.169160             0.692225                  2
14 -19.4  214.276120           172.083880                  3
48 -19.4  386.796300            -0.436300                  3
61 -18.7    0.619703            -0.768702                  2
63 -18.6    0.302509            -0.549482                  2
..   ...         ...                  ...                ...
55  18.6   94.105940           -57.029430                  1
86  18.8  363.701540            -0.261540                  3
27  19.0   74.764200           -36.689260                  1
30  19.4   77.410530           -38.349000                  1
13  19.7   18.980263             0.846235                  0

[100 rows x 4 columns]

In [4]:
test

       x           y  Delta Y (test func)  No. of ideal func
0   12.6  257.215420           -88.455420                  3
1  -14.9    0.267808             0.455074                  2
2   -4.5    6.118259            -1.093322                  0
3    2.4    5.181103            -0.043371                  1
4  -17.9   -0.845322             0.032164                  2
..   ...         ...                  ...                ...
95   7.3   14.125660             0.899558                  1
96 -10.0  -25.212278             5.484288                  1
97 -19.4   -0.169160             0.692225                  2
98  11.0   22.082275            -0.582269                  1
99  10.4  117.566230             0.593770                  3

[100 rows x 4 columns]

In [5]:
train = pd.read_csv('train.csv', index_col = 0)
train

              y1         y2        y3         y4
x
-20.0  19.794191 -40.422230  1.089534  409.53973
-19.9  19.808426 -40.516800  0.800835  405.70517
-19.8  19.915476 -39.584960  1.095554  401.80957
-19.7  19.715796 -39.989166  1.161140  397.87543
-19.6  19.642672 -39.418360  0.365370  394.22790
...          ...        ...       ...        ...
 19.5  19.450926  39.161300 -0.482247  390.46017
 19.6  19.944368  39.720966 -1.082964  393.94876
 19.7  20.189590  39.817450 -0.425631  397.94064
 19.8  19.973238  39.968720 -1.074738  402.41840
 19.9  19.593924  39.922030 -0.868087  405.54385

[400 rows x 4 columns]

In [6]:
ideal = pd.read_csv('ideal.csv', index_col = 0)
ideal

,y1,y2,y3,y4,y5,y6,y7,y8,y9,y10,...,y41,y42,y43,y44,y45,y46,y47,y48,y49,y50
x,,,,,,,,,,,,,,,,,,,,,
-20.0,-0.912945,0.408082,9.087055,5.408082,-9.087055,0.912945,-0.839071,-0.850919,0.816164,18.258905,...,-40.456474,40.204040,2.995732,-0.008333,12.995732,5.298317,-5.298317,-0.186278,0.912945,0.396850
-19.9,-0.867644,0.497186,9.132356,5.497186,-9.132356,0.867644,-0.865213,0.168518,0.994372,17.266117,...,-40.233820,40.048590,2.990720,-0.008340,12.990720,5.293305,-5.293305,-0.215690,0.867644,0.476954
-19.8,-0.813674,0.581322,9.186326,5.581322,-9.186326,0.813674,-0.889191,0.612391,1.162644,16.110740,...,-40.006836,39.890660,2.985682,-0.008347,12.985682,5.288267,-5.288267,-0.236503,0.813674,0.549129
-19.7,-0.751573,0.659649,9.248426,5.659649,-9.248426,0.751573,-0.910947,-0.994669,1.319299,14.805996,...,-39.775787,39.729824,2.980619,-0.008354,12.980619,5.283204,-5.283204,-0.247887,0.751573,0.612840
-19.6,-0.681964,0.731386,9.318036,5.731386,-9.318036,0.681964,-0.930426,0.774356,1.462772,13.366487,...,-39.540980,39.565693,2.975530,-0.008361,12.975530,5.278115,-5.278115,-0.249389,0.681964,0.667902
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19.5,0.605540,0.795815,10.605540,5.795815,-10.605540,-0.605540,-0.947580,-0.117020,1.591630,11.808027,...,39.302770,-38.602093,2.970414,-0.012422,12.970414,5.273000,-5.273000,0.240949,0.605540,0.714434
19.6,0.681964,0.731386,10.681964,5.731386,-10.681964,-0.681964,-0.930426,0.774356,1.462772,13.366487,...,39.540980,-38.834310,2.975530,-0.012438,12.975530,5.278115,-5.278115,0.249389,0.681964,0.667902
19.7,0.751573,0.659649,10.751574,5.659649,-10.751574,-0.751573,-0.910947,-0.994669,1.319299,14.805996,...,39.775787,-39.070175,2.980619,-0.012453,12.980619,5.283204,-5.283204,0.247887,0.751573,0.612840
19.8,0.813674,0.581322,10.813674,5.581322,-10.813674,-0.813674,-0.889191,0.612391,1.162644,16.110740,...,40.006836,-39.309338,2.985682,-0.012469,12.985682,5.288267,-5.288267,0.236503,0.813674,0.549129
19.9,0.867644,0.497186,10.867644,5.497186,-10.867644,-0.867644,-0.865213,0.168518,0.994372,17.266117,...,40.233820,-39.551407,2.990720,-0.012484,12.990720,5.293305,-5.293305,0.215690,0.867644,0.476954

In [7]:
def MSE(train):
    mse = []
    for i in range(1, 51):
        i = str(i)
        mse.append(sum((train - ideal["y" + i]) ** 2) / len(train))
        
    return mse.index(min(mse)) + 1, min(mse)

In [8]:
def MSE_ALL(train):
    mse_all = []
    for i in range(1, 5):
        i = str(i)
        mse_all.append(MSE(train["y" + i]))
    
    return mse_all

In [9]:
MSE_ALL(train)

[(33, 0.08056848922483674),
 (41, 0.08621440844128392),
 (6, 0.08519682325505325),
 (19, 0.07511489956278368)]

In [10]:
def Ideal_Dataset(train):
    dataset = []
    for i in range(4):
        dataset.append(ideal["y" + str(MSE_ALL(train)[i][0])])
        
    return dataset

In [11]:
Ideal_Dataset(train)

[x
 -20.0    20.124610
 -19.9    20.025234
 -19.8    19.925863
 -19.7    19.826498
 -19.6    19.727139
            ...
  19.5    19.627787
  19.6    19.727139
  19.7    19.826498
  19.8    19.925863
  19.9    20.025234
 Name: y33, Length: 400, dtype: float64,
 x
 -20.0   -40.456474
 -19.9   -40.233820
 -19.8   -40.006836
 -19.7   -39.775787
 -19.6   -39.540980
            ...
  19.5    39.302770
  19.6    39.540980
  19.7    39.775787
  19.8    40.006836
  19.9    40.233820
 Name: y41, Length: 400, dtype: float64,
 x
 -20.0    0.912945
 -19.9    0.867644
 -19.8    0.813674
 -19.7    0.751573
 -19.6    0.681964
            ...
  19.5   -0.605540
  19.6   -0.681964
  19.7   -0.751573
  19.8   -0.813674
  19.9   -0.867644
 Name: y6, Length: 400, dtype: float64,
 x
 -20.0    410.00
 -19.9    406.01
 -19.8    402.04
 -19.7    398.09
 -19.6    394.16
           ...
  19.5    390.25
  19.6    394.16
  19.7    398.09
  19.8    402.04
  19.9    406.01
 Name: y19, Length: 400, dtype: float64]

In [12]:
test.iloc[0, 0]

12.6

In [13]:
train.index == test.iloc[0, 0]

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False])

In [14]:
train[train.index == test.iloc[0, 0]]

             y1         y2        y3         y4
x
12.6  12.351159  24.856575 -0.382316  168.73499

In [15]:
train.y1[train.index == test.iloc[0, 0]]

x
12.6    12.351159
Name: y1, dtype: float64

In [16]:
train.y1[train.index == test.iloc[0, 0]].iloc[0]

12.351158999999999

In [17]:
Ideal_Dataset(train)[0]

x
-20.0    20.124610
-19.9    20.025234
-19.8    19.925863
-19.7    19.826498
-19.6    19.727139
           ...
 19.5    19.627787
 19.6    19.727139
 19.7    19.826498
 19.8    19.925863
 19.9    20.025234
Name: y33, Length: 400, dtype: float64

In [18]:
Ideal_Dataset(train)[0][Ideal_Dataset(train)[0].index == test.iloc[0, 0]]

x
12.6    12.796875
Name: y33, dtype: float64

In [19]:
Ideal_Dataset(train)[0][train.index == test.iloc[0, 0]]

x
12.6    12.796875
Name: y33, dtype: float64

In [20]:
Ideal_Dataset(train)[0][train.index == test.iloc[0, 0]].iloc[0]

12.796875

In [21]:
Ideal_Dataset(train)[0][train.index == test.iloc[0, 0]].iloc[0] \
- train.y1[train.index == test.iloc[0, 0]].iloc[0]

0.4457160000000009

In [22]:
dev1 = Ideal_Dataset(train)[0][train.index == test.iloc[0, 0]].iloc[0] \
- train.y1[train.index == test.iloc[0, 0]].iloc[0]
dev1

0.4457160000000009

In [23]:
dev2 = Ideal_Dataset(train)[1][train.index == test.iloc[0, 0]].iloc[0] \
- train.y2[train.index == test.iloc[0, 0]].iloc[0]
dev2

0.3602370000000015

In [24]:
dev3 = Ideal_Dataset(train)[2][train.index == test.iloc[0, 0]].iloc[0] \
- train.y3[train.index == test.iloc[0, 0]].iloc[0]
dev3

0.348692733

In [25]:
dev4 = Ideal_Dataset(train)[3][train.index == test.iloc[0, 0]].iloc[0] \
- train.y4[train.index == test.iloc[0, 0]].iloc[0]
dev4

0.02501000000000886

In [26]:
max([dev1, dev2, dev3, dev4])

0.4457160000000009

In [27]:
Dev = []
for i in range(4):
    dev = Ideal_Dataset(train)[i][train.index == test.iloc[0, 0]].iloc[0] \
- train["y" + str(i + 1)][train.index == test.iloc[0, 0]].iloc[0]
    Dev.append(dev)

print(Dev)

[0.4457160000000009, 0.3602370000000015, 0.348692733, 0.02501000000000886]

In [28]:
max(Dev)

0.4457160000000009

In [29]:
def Dev_Max_0(train):
    Dev = []
    for i in range(4):
        dev = Ideal_Dataset(train)[i][train.index == test.iloc[0, 0]].iloc[0] \
    - train["y" + str(i + 1)][train.index == test.iloc[0, 0]].iloc[0]
        Dev.append(dev)
        
    return max(Dev)

In [30]:
Dev_Max_0(train)

0.4457160000000009

In [31]:
Dev = []
for i in range(4):
    dev = Ideal_Dataset(train)[i][train.index == test.iloc[1, 0]].iloc[0] \
- train["y" + str(i + 1)][train.index == test.iloc[1, 0]].iloc[0]
    Dev.append(dev)

print(Dev)

[-0.35021899999999917, -0.4151120000000006, 0.1637731, 0.2798700000000167]

In [32]:
max(Dev)

0.2798700000000167

In [33]:
max(Dev, key = abs)

-0.4151120000000006

In [34]:
def Dev_Max_1(train):
    Dev = []
    for i in range(4):
        dev = Ideal_Dataset(train)[i][train.index == test.iloc[1, 0]].iloc[0] \
    - train["y" + str(i + 1)][train.index == test.iloc[1, 0]].iloc[0]
        Dev.append(dev)
        
    return max(Dev, key = abs)

In [35]:
Dev_Max_1(train)

-0.4151120000000006

In [36]:
def Dev_Max(train, j):
    Dev = []
    for i in range(4):
        dev = Ideal_Dataset(train)[i][train.index == test.iloc[j, 0]].iloc[0] \
    - train["y" + str(i + 1)][train.index == test.iloc[j, 0]].iloc[0]
        Dev.append(dev)
        
    return max(Dev, key = abs)

In [37]:
Dev_Max(train, 0)

0.4457160000000009

In [38]:
Dev_Max(train, 1)

-0.4151120000000006

In [39]:
len(test)

100

In [40]:
def Dev_Max_ALL(train):
    Dev_all = []
    for i in range(len(test)):
        dev_abmax = Dev_Max(train, i)
        Dev_all.append(dev_abmax)
    return Dev_all

In [41]:
Dev_ALL = Dev_Max_ALL(train)
Dev_ALL

[0.4457160000000009,
 -0.4151120000000006,
 0.4959270000000001,
 0.3243521400000001,
 0.39629799999999804,
 -0.3550930000000001,
 -0.4612410000000011,
 -0.2691440000000007,
 -0.479357836,
 -0.4259500000000003,
 0.4689770000000024,
 0.4614700000000198,
 -0.4189179999999997,
 -0.3630919999999982,
 -0.2863340000000001,
 0.4804047000000007,
 -0.4113643999999992,
 -0.42501569999999944,
 0.49495199999999784,
 -0.4329699999999974,
 0.3867580999999993,
 -0.4482759999999999,
 -0.41661200000000065,
 0.4483740000000003,
 -0.4516146999999995,
 0.4793520000000001,
 -0.49720400000000353,
 -0.23658999999999253,
 -0.33885147000000004,
 -0.38822741,
 0.3496929999999985,
 -0.38315000000000055,
 0.3991502999999996,
 0.3815098,
 0.49264156000000026,
 0.4617322600000001,
 0.42753999999999337,
 -0.38300999999999874,
 0.44614899999999924,
 -0.26631049999999945,
 -0.3137475999999997,
 0.43006000000002587,
 0.49184999999999945,
 -0.40334849999999994,
 -0.44767699999999877,
 0.2941754999999997,
 -0.4298812000000001,
 -0.4858005499999999,
 -0.2863340000000001,
 -0.40934066,
 -0.43734578999999996,
 -0.32230364999999983,
 -0.4151120000000006,
 -0.45511314,
 0.3659699999999759,
 0.46756999999999493,
 0.4439530000000005,
 0.48537144,
 -0.2788240000000002,
 -0.4132308999999994,
 0.2822500000000048,
 -0.3541939999999997,
 -0.4259500000000003,
 0.26514200000000443,
 0.39245025,
 -0.42887911999999995,
 0.4007668000000001,
 -0.3550576000000003,
 0.30580749999999846,
 0.49724,
 -0.49098799999999976,
 0.4677705000000021,
 -0.45830618599999995,
 -0.49098799999999976,
 -0.31683000000001016,
 0.4649669999999997,
 -0.4501880000000007,
 -0.4009099999999961,
 -0.4453579999999988,
 -0.41842016299999996,
 -0.3518220000000003,
 0.48715100000000255,
 -0.42003200000000085,
 -0.22898196999999998,
 -0.40869299999999953,
 -0.4593779999999974,
 0.3035409999999992,
 0.49495199999999784,
 -0.43146967999999997,
 -0.4127950000000009,
 0.4472529999999999,
 0.4379860000000022,
 -0.3443320000000001,
 -0.49720400000000353,
 0.4439530000000005,
 -0.24706700000000037,
 -0.45830618599999995,
 -0.2863340000000001,
 -0.4174869000000001,
 -0.3811169999999997]

In [42]:
test.insert(4, "Max. of deviation", Dev_ALL, True)
test

,x,y,Delta Y (test func),No. of ideal func,Max. of deviation
0,12.6,257.215420,-88.455420,3,0.445716
1,-14.9,0.267808,0.455074,2,-0.415112
2,-4.5,6.118259,-1.093322,0,0.495927
3,2.4,5.181103,-0.043371,1,0.324352
4,-17.9,-0.845322,0.032164,2,0.396298
...,...,...,...,...,...
95,7.3,14.125660,0.899558,1,-0.247067
96,-10.0,-25.212278,5.484288,1,-0.458306
97,-19.4,-0.169160,0.692225,2,-0.286334
98,11.0,22.082275,-0.582269,1,-0.417487
99,10.4,117.566230,0.593770,3,-0.381117

In [43]:
test.to_csv('Table 3+.csv', header = True, index = False)