In [1]:
import pandas as pd

In [2]:
"""Open the training datasets."""
train = pd.read_csv('train.csv', index_col = 0)
train

              y1         y2        y3         y4
x
-20.0  19.794191 -40.422230  1.089534  409.53973
-19.9  19.808426 -40.516800  0.800835  405.70517
-19.8  19.915476 -39.584960  1.095554  401.80957
-19.7  19.715796 -39.989166  1.161140  397.87543
-19.6  19.642672 -39.418360  0.365370  394.22790
...          ...        ...       ...        ...
 19.5  19.450926  39.161300 -0.482247  390.46017
 19.6  19.944368  39.720966 -1.082964  393.94876
 19.7  20.189590  39.817450 -0.425631  397.94064
 19.8  19.973238  39.968720 -1.074738  402.41840
 19.9  19.593924  39.922030 -0.868087  405.54385

[400 rows x 4 columns]

In [3]:
"""Open the ideal datasets."""
ideal = pd.read_csv('ideal.csv', index_col = 0)
ideal

,y1,y2,y3,y4,y5,y6,y7,y8,y9,y10,...,y41,y42,y43,y44,y45,y46,y47,y48,y49,y50
x,,,,,,,,,,,,,,,,,,,,,
-20.0,-0.912945,0.408082,9.087055,5.408082,-9.087055,0.912945,-0.839071,-0.850919,0.816164,18.258905,...,-40.456474,40.204040,2.995732,-0.008333,12.995732,5.298317,-5.298317,-0.186278,0.912945,0.396850
-19.9,-0.867644,0.497186,9.132356,5.497186,-9.132356,0.867644,-0.865213,0.168518,0.994372,17.266117,...,-40.233820,40.048590,2.990720,-0.008340,12.990720,5.293305,-5.293305,-0.215690,0.867644,0.476954
-19.8,-0.813674,0.581322,9.186326,5.581322,-9.186326,0.813674,-0.889191,0.612391,1.162644,16.110740,...,-40.006836,39.890660,2.985682,-0.008347,12.985682,5.288267,-5.288267,-0.236503,0.813674,0.549129
-19.7,-0.751573,0.659649,9.248426,5.659649,-9.248426,0.751573,-0.910947,-0.994669,1.319299,14.805996,...,-39.775787,39.729824,2.980619,-0.008354,12.980619,5.283204,-5.283204,-0.247887,0.751573,0.612840
-19.6,-0.681964,0.731386,9.318036,5.731386,-9.318036,0.681964,-0.930426,0.774356,1.462772,13.366487,...,-39.540980,39.565693,2.975530,-0.008361,12.975530,5.278115,-5.278115,-0.249389,0.681964,0.667902
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19.5,0.605540,0.795815,10.605540,5.795815,-10.605540,-0.605540,-0.947580,-0.117020,1.591630,11.808027,...,39.302770,-38.602093,2.970414,-0.012422,12.970414,5.273000,-5.273000,0.240949,0.605540,0.714434
19.6,0.681964,0.731386,10.681964,5.731386,-10.681964,-0.681964,-0.930426,0.774356,1.462772,13.366487,...,39.540980,-38.834310,2.975530,-0.012438,12.975530,5.278115,-5.278115,0.249389,0.681964,0.667902
19.7,0.751573,0.659649,10.751574,5.659649,-10.751574,-0.751573,-0.910947,-0.994669,1.319299,14.805996,...,39.775787,-39.070175,2.980619,-0.012453,12.980619,5.283204,-5.283204,0.247887,0.751573,0.612840
19.8,0.813674,0.581322,10.813674,5.581322,-10.813674,-0.813674,-0.889191,0.612391,1.162644,16.110740,...,40.006836,-39.309338,2.985682,-0.012469,12.985682,5.288267,-5.288267,0.236503,0.813674,0.549129
19.9,0.867644,0.497186,10.867644,5.497186,-10.867644,-0.867644,-0.865213,0.168518,0.994372,17.266117,...,40.233820,-39.551407,2.990720,-0.012484,12.990720,5.293305,-5.293305,0.215690,0.867644,0.476954

In [4]:
"""See the y1 column in the training datasets."""
train.y1 = train['y1']
train.y1

x
-20.0    19.794191
-19.9    19.808426
-19.8    19.915476
-19.7    19.715796
-19.6    19.642672
           ...
 19.5    19.450926
 19.6    19.944368
 19.7    20.189590
 19.8    19.973238
 19.9    19.593924
Name: y1, Length: 400, dtype: float64

In [5]:
"""See the y1 column in the ideal datasets"""
ideal.y1 = ideal['y1']
ideal.y1

x
-20.0   -0.912945
-19.9   -0.867644
-19.8   -0.813674
-19.7   -0.751573
-19.6   -0.681964
           ...
 19.5    0.605540
 19.6    0.681964
 19.7    0.751573
 19.8    0.813674
 19.9    0.867644
Name: y1, Length: 400, dtype: float64

In [6]:
"""Calculate the differences."""
(train.y1 - ideal.y1)

x
-20.0    20.707136
-19.9    20.676070
-19.8    20.729150
-19.7    20.467369
-19.6    20.324636
           ...
 19.5    18.845386
 19.6    19.262404
 19.7    19.438017
 19.8    19.159564
 19.9    18.726280
Name: y1, Length: 400, dtype: float64

In [7]:
"""Sqaure the differences."""
(train.y1 - ideal.y1) ** 2

x
-20.0    428.785494
-19.9    427.499875
-19.8    429.697649
-19.7    418.913212
-19.6    413.090812
            ...
 19.5    355.148579
 19.6    371.040223
 19.7    377.836488
 19.8    367.088903
 19.9    350.673559
Name: y1, Length: 400, dtype: float64

In [8]:
"""Sum up the differences"""
sum((train.y1 - ideal.y1) ** 2)

55511.37465220096

In [9]:
"""Find the the number of these rows"""
len(train), len(ideal)

(400, 400)

In [10]:
"""This is the Mean Squared Error (MSE) for train.y1 and ideal.y1."""
sum((train.y1 - ideal.y1) ** 2) / len(train)

138.7784366305024

In [11]:
"""Exception handlings for the MSE."""
try:
    result = sum((train.y1 - ideal.y1) ** 2) / len(train)
    print('MSE between train.y1 and ideal.y1 is: {}'.format(result))
except Exception as e:
    print('Calculation error')
    print(e)
else:
    print('No error')
finally:
    print('End')

MSE between train.y1 and ideal.y1 is: 138.7784366305024
No error
End

In [12]:
"""See the y2 column in the ideal datasets"""
ideal.y2

x
-20.0    0.408082
-19.9    0.497186
-19.8    0.581322
-19.7    0.659649
-19.6    0.731386
           ...
 19.5    0.795815
 19.6    0.731386
 19.7    0.659649
 19.8    0.581322
 19.9    0.497186
Name: y2, Length: 400, dtype: float64

In [13]:
"""This is the MSE for train.y1 and ideal.y2."""
sum((train.y1 - ideal.y2) ** 2) / len(train)

136.8677836559274

In [14]:
"""Calculate the smallest MSE for train.y1 and ideal.y1 - ideal.y50 to find the best function."""
MSE1 = []
for i in range(1, 51):
    i = str(i)
    MSE1.append(sum((train.y1 - ideal["y" + i]) ** 2) / len(train))
    
print(MSE1.index(min(MSE1)) + 1)

33

In [15]:
"""Create a function to calculate the smallest MSE."""
def MSE(train):
    mse = []
    for i in range(1, 51):
        i = str(i)
        mse.append(sum((train - ideal["y" + i]) ** 2) / len(train))
        
    return mse.index(min(mse)) + 1, min(mse)

In [16]:
"""The smallest MSE for train.y1"""
MSE(train.y1)

(33, 0.08056848922483674)

In [17]:
"""The smallest MSE for train.y2."""
MSE(train.y2)

(41, 0.08621440844128392)

In [18]:
"""The smallest MSE for train.y3."""
MSE(train.y3)

(6, 0.08519682325505325)

In [19]:
"""The smallest MSE for train.y4."""
MSE(train.y4)

(19, 0.07511489956278368)

In [20]:
"""Exception handlings for the function."""
try:
    result = MSE(train.y1)
    print('The minimum MSE between train.y1 and ideal.y1 - ideal.y50 is:\
    {}'.format(result))
except Exception as e:
    print('Calculation error')
    print(e)
else:
    print('No error')
finally:
    print('End')

The minimum MSE between train.y1 and ideal.y1 - ideal.y50 is:    (33, 0.08056848922483674)
No error
End

In [21]:
"""Calculate the smallest MSE for train.y1 - train.y4 at one time."""
for i in range(1, 5):
    i = str(i)
    print(MSE(train["y" + i]))

(33, 0.08056848922483674)
(41, 0.08621440844128392)
(6, 0.08519682325505325)
(19, 0.07511489956278368)

In [22]:
"""Create a function to calcuate the MSEs."""
def MSE_ALL(train):
    mse_all = []
    for i in range(1, 5):
        i = str(i)
        mse_all.append(MSE(train["y" + i]))
    return mse_all

In [23]:
"""They are the smallest MSE for train.y1 - train.y4."""
MSE_ALL(train)

[(33, 0.08056848922483674),
 (41, 0.08621440844128392),
 (6, 0.08519682325505325),
 (19, 0.07511489956278368)]

In [24]:
"""The best function and the MSE for train.y1"""
MSE_ALL(train)[0]

(33, 0.08056848922483674)

In [25]:
"""Ideal.y33 is the best function for train.y1."""
MSE_ALL(train)[0][0]

33

In [26]:
"""See ideal.y33."""
ideal.y33

x
-20.0    20.124610
-19.9    20.025234
-19.8    19.925863
-19.7    19.826498
-19.6    19.727139
           ...
 19.5    19.627787
 19.6    19.727139
 19.7    19.826498
 19.8    19.925863
 19.9    20.025234
Name: y33, Length: 400, dtype: float64

In [27]:
type(MSE_ALL(train)[0][0])

int

In [28]:
"""This is the formula to find the best function for train.y1."""
ideal["y" + str(MSE_ALL(train)[0][0])]

x
-20.0    20.124610
-19.9    20.025234
-19.8    19.925863
-19.7    19.826498
-19.6    19.727139
           ...
 19.5    19.627787
 19.6    19.727139
 19.7    19.826498
 19.8    19.925863
 19.9    20.025234
Name: y33, Length: 400, dtype: float64

In [29]:
"""Exception handlings for the formula."""
try:
    result = ideal["y" + str(MSE_ALL(train)[0][0])]
    print('The ideal dataset for train.y1 is:\
    {}'.format(result))
except Exception as e:
    print('Calculation error')
    print(e)
else:
    print('No error')
finally:
    print('End')

The ideal dataset for train.y1 is:    x
-20.0    20.124610
-19.9    20.025234
-19.8    19.925863
-19.7    19.826498
-19.6    19.727139
           ...
 19.5    19.627787
 19.6    19.727139
 19.7    19.826498
 19.8    19.925863
 19.9    20.025234
Name: y33, Length: 400, dtype: float64
No error
End

In [30]:
"""Exception handlings for the formula to find the best function."""
try:
    result = ideal["y" + str(MSE_ALL(train)[0][0])]
    print('The ideal dataset for train.y1 is:{}'.format(result))
except Exception as e:
    print('Calculation error')
    print(e)
else:
    print('No error')
finally:
    print('End')

The ideal dataset for train.y1 is:x
-20.0    20.124610
-19.9    20.025234
-19.8    19.925863
-19.7    19.826498
-19.6    19.727139
           ...
 19.5    19.627787
 19.6    19.727139
 19.7    19.826498
 19.8    19.925863
 19.9    20.025234
Name: y33, Length: 400, dtype: float64
No error
End

In [31]:
"""Exception handlings for the MSE function."""
try:
    result = MSE(train.y1)
    print('The minimum MSE between train.y1 and ideal.y1-ideal.y50 is:{}'.format(result))
except Exception as e:
    print('Calculation error')
    print(e)
else:
    print('No error')
finally:
    print('End')

The minimum MSE between train.y1 and ideal.y1-ideal.y50 is:(33, 0.08056848922483674)
No error
End

In [32]:
"""Exception handlings for the formula to find the best function."""
try:
    result = ideal["y" + (MSE_ALL(train)[0][0])]
    print('The ideal dataset for train.y1 is:{}'.format(result))
except Exception as e:
    print('Calculation error')
    print(e)
else:
    print('No error')
finally:
    print('End')

Calculation error
can only concatenate str (not "int") to str
End

In [33]:
"""Exception handlings for the formula to find the best function."""
try:
    result = ideal["y" + (MSE_ALL(train)[0][0])]
    print('The ideal dataset for train.y1 is:{}'.format(result))
except TypeError as e:
    print('Wrong type')
    print(e)
except Exception as e:
    print('Calculation error')
    print(e)
else:
    print('No error')
finally:
    print('End')

Wrong type
can only concatenate str (not "int") to str
End

In [34]:
"""This is the function to extract the four best functions from the ideal datasets."""
def Ideal_Dataset(train):
    dataset = []
    for i in range(4):
        dataset.append(ideal["y" + str(MSE_ALL(train)[i][0])])
    return dataset

In [35]:
"""They are the four best functions."""
Ideal_Dataset(train)

[x
 -20.0    20.124610
 -19.9    20.025234
 -19.8    19.925863
 -19.7    19.826498
 -19.6    19.727139
            ...
  19.5    19.627787
  19.6    19.727139
  19.7    19.826498
  19.8    19.925863
  19.9    20.025234
 Name: y33, Length: 400, dtype: float64,
 x
 -20.0   -40.456474
 -19.9   -40.233820
 -19.8   -40.006836
 -19.7   -39.775787
 -19.6   -39.540980
            ...
  19.5    39.302770
  19.6    39.540980
  19.7    39.775787
  19.8    40.006836
  19.9    40.233820
 Name: y41, Length: 400, dtype: float64,
 x
 -20.0    0.912945
 -19.9    0.867644
 -19.8    0.813674
 -19.7    0.751573
 -19.6    0.681964
            ...
  19.5   -0.605540
  19.6   -0.681964
  19.7   -0.751573
  19.8   -0.813674
  19.9   -0.867644
 Name: y6, Length: 400, dtype: float64,
 x
 -20.0    410.00
 -19.9    406.01
 -19.8    402.04
 -19.7    398.09
 -19.6    394.16
           ...
  19.5    390.25
  19.6    394.16
  19.7    398.09
  19.8    402.04
  19.9    406.01
 Name: y19, Length: 400, dtype: float64]

In [36]:
"""Define the four functions as 'ideal_four' to reduce information."""
ideal_four = Ideal_Dataset(train)
ideal_four

[x
 -20.0    20.124610
 -19.9    20.025234
 -19.8    19.925863
 -19.7    19.826498
 -19.6    19.727139
            ...
  19.5    19.627787
  19.6    19.727139
  19.7    19.826498
  19.8    19.925863
  19.9    20.025234
 Name: y33, Length: 400, dtype: float64,
 x
 -20.0   -40.456474
 -19.9   -40.233820
 -19.8   -40.006836
 -19.7   -39.775787
 -19.6   -39.540980
            ...
  19.5    39.302770
  19.6    39.540980
  19.7    39.775787
  19.8    40.006836
  19.9    40.233820
 Name: y41, Length: 400, dtype: float64,
 x
 -20.0    0.912945
 -19.9    0.867644
 -19.8    0.813674
 -19.7    0.751573
 -19.6    0.681964
            ...
  19.5   -0.605540
  19.6   -0.681964
  19.7   -0.751573
  19.8   -0.813674
  19.9   -0.867644
 Name: y6, Length: 400, dtype: float64,
 x
 -20.0    410.00
 -19.9    406.01
 -19.8    402.04
 -19.7    398.09
 -19.6    394.16
           ...
  19.5    390.25
  19.6    394.16
  19.7    398.09
  19.8    402.04
  19.9    406.01
 Name: y19, Length: 400, dtype: float64]

In [37]:
ideal_four[0]

x
-20.0    20.124610
-19.9    20.025234
-19.8    19.925863
-19.7    19.826498
-19.6    19.727139
           ...
 19.5    19.627787
 19.6    19.727139
 19.7    19.826498
 19.8    19.925863
 19.9    20.025234
Name: y33, Length: 400, dtype: float64

In [38]:
"""This is a class to calculate the difference between train.y1 and ideal.y33."""
class Train_Ideal:
    
    def __init__(self):        
        self.train = train
        self.ideal = ideal
    
    def Difference(self):
        difference = self.train.y1 - self.ideal.y33
        return difference

In [39]:
Train_Ideal

__main__.Train_Ideal

In [40]:
Train_Ideal()

In [41]:
Train_Ideal.Difference

In [42]:
Train_Ideal().Difference

In [43]:
"""This is the difference between train.y1 and ideal.y33."""
Train_Ideal().Difference()

x
-20.0   -0.330419
-19.9   -0.216808
-19.8   -0.010387
-19.7   -0.110702
-19.6   -0.084467
           ...
 19.5   -0.176861
 19.6    0.217229
 19.7    0.363092
 19.8    0.047375
 19.9   -0.431310
Length: 400, dtype: float64

In [44]:
def MSE(train):
    mse = []
    for i in range(1, 51):
        i = str(i)
        mse.append(sum((train - ideal["y" + i]) ** 2) / len(train))
        
    return mse.index(min(mse)) + 1, min(mse)

In [45]:
def MSE_ALL(train):
    mse_all = []
    for i in range(1, 5):
        i = str(i)
        mse_all.append(MSE(train["y" + i]))
    
    return mse_all

In [46]:
def Ideal_Dataset(train):
    dataset = []
    for i in range(4):
        dataset.append(ideal["y" + str(MSE_ALL(train)[i][0])])
        
    return dataset

In [47]:
ideal_four = Ideal_Dataset(train)
ideal_four

[x
 -20.0    20.124610
 -19.9    20.025234
 -19.8    19.925863
 -19.7    19.826498
 -19.6    19.727139
            ...
  19.5    19.627787
  19.6    19.727139
  19.7    19.826498
  19.8    19.925863
  19.9    20.025234
 Name: y33, Length: 400, dtype: float64,
 x
 -20.0   -40.456474
 -19.9   -40.233820
 -19.8   -40.006836
 -19.7   -39.775787
 -19.6   -39.540980
            ...
  19.5    39.302770
  19.6    39.540980
  19.7    39.775787
  19.8    40.006836
  19.9    40.233820
 Name: y41, Length: 400, dtype: float64,
 x
 -20.0    0.912945
 -19.9    0.867644
 -19.8    0.813674
 -19.7    0.751573
 -19.6    0.681964
            ...
  19.5   -0.605540
  19.6   -0.681964
  19.7   -0.751573
  19.8   -0.813674
  19.9   -0.867644
 Name: y6, Length: 400, dtype: float64,
 x
 -20.0    410.00
 -19.9    406.01
 -19.8    402.04
 -19.7    398.09
 -19.6    394.16
           ...
  19.5    390.25
  19.6    394.16
  19.7    398.09
  19.8    402.04
  19.9    406.01
 Name: y19, Length: 400, dtype: float64]

In [48]:
"""This is a class to combine the three functions showned above to find the four functions."""
class Ideal_Four:
    
    def __init__(self):
        self.ideal = ideal
        
    def MSE(self, train):
        mse = []
        for i in range(1, 51):
            i = str(i)
            mse.append(sum((train - self.ideal["y" + i]) ** 2) /\
                       len(train))

        return mse.index(min(mse)) + 1, min(mse)
    
    def MSE_ALL(self, train):
        mse_all = []
        for i in range(1, 5):
            i = str(i)
            mse_all.append(self.MSE(train["y" + i]))

        return mse_all
    
    def Ideal_Dataset(self, train):
        dataset = []
        for i in range(4):
            dataset.append(self.ideal\
                           ["y" + str(self.MSE_ALL(train)[i][0])])

        return dataset

In [49]:
Ideal_Four

__main__.Ideal_Four

In [50]:
Ideal_Four()

In [51]:
"""The class produces the same results."""
Ideal_Four().MSE(train.y1)

(33, 0.08056848922483674)

In [52]:
"""The class produces the same results."""
Ideal_Four().MSE(train.y2)

(41, 0.08621440844128392)

In [53]:
"""The class produces the same results."""
Ideal_Four().MSE(train.y3)

(6, 0.08519682325505325)

In [54]:
"""The class produces the same results."""
Ideal_Four().MSE(train.y4)

(19, 0.07511489956278368)

In [55]:
"""The class produces the same results."""
Ideal_Four().MSE_ALL(train)

[(33, 0.08056848922483674),
 (41, 0.08621440844128392),
 (6, 0.08519682325505325),
 (19, 0.07511489956278368)]

In [56]:
"""The class produces the same results."""
Ideal_Four().Ideal_Dataset(train)

[x
 -20.0    20.124610
 -19.9    20.025234
 -19.8    19.925863
 -19.7    19.826498
 -19.6    19.727139
            ...
  19.5    19.627787
  19.6    19.727139
  19.7    19.826498
  19.8    19.925863
  19.9    20.025234
 Name: y33, Length: 400, dtype: float64,
 x
 -20.0   -40.456474
 -19.9   -40.233820
 -19.8   -40.006836
 -19.7   -39.775787
 -19.6   -39.540980
            ...
  19.5    39.302770
  19.6    39.540980
  19.7    39.775787
  19.8    40.006836
  19.9    40.233820
 Name: y41, Length: 400, dtype: float64,
 x
 -20.0    0.912945
 -19.9    0.867644
 -19.8    0.813674
 -19.7    0.751573
 -19.6    0.681964
            ...
  19.5   -0.605540
  19.6   -0.681964
  19.7   -0.751573
  19.8   -0.813674
  19.9   -0.867644
 Name: y6, Length: 400, dtype: float64,
 x
 -20.0    410.00
 -19.9    406.01
 -19.8    402.04
 -19.7    398.09
 -19.6    394.16
           ...
  19.5    390.25
  19.6    394.16
  19.7    398.09
  19.8    402.04
  19.9    406.01
 Name: y19, Length: 400, dtype: float64]

In [57]:
"""Define the results as 'Ideal_Four' to reduce information."""
Ideal_four = Ideal_Four().Ideal_Dataset(train)
Ideal_four

[x
 -20.0    20.124610
 -19.9    20.025234
 -19.8    19.925863
 -19.7    19.826498
 -19.6    19.727139
            ...
  19.5    19.627787
  19.6    19.727139
  19.7    19.826498
  19.8    19.925863
  19.9    20.025234
 Name: y33, Length: 400, dtype: float64,
 x
 -20.0   -40.456474
 -19.9   -40.233820
 -19.8   -40.006836
 -19.7   -39.775787
 -19.6   -39.540980
            ...
  19.5    39.302770
  19.6    39.540980
  19.7    39.775787
  19.8    40.006836
  19.9    40.233820
 Name: y41, Length: 400, dtype: float64,
 x
 -20.0    0.912945
 -19.9    0.867644
 -19.8    0.813674
 -19.7    0.751573
 -19.6    0.681964
            ...
  19.5   -0.605540
  19.6   -0.681964
  19.7   -0.751573
  19.8   -0.813674
  19.9   -0.867644
 Name: y6, Length: 400, dtype: float64,
 x
 -20.0    410.00
 -19.9    406.01
 -19.8    402.04
 -19.7    398.09
 -19.6    394.16
           ...
  19.5    390.25
  19.6    394.16
  19.7    398.09
  19.8    402.04
  19.9    406.01
 Name: y19, Length: 400, dtype: float64]

In [58]:
Ideal_Four().MSE(train.y1)

(33, 0.08056848922483674)

In [59]:
Ideal_Four().MSE_ALL(train)[1]

(41, 0.08621440844128392)

In [60]:
Ideal_Four().Ideal_Dataset(train)[0].iloc[0]

20.12461

In [61]:
"""Perform unittest for the class to verify its accuracy."""
import unittest
from unittest import TestCase

class TestIdeal_Four(unittest.TestCase):
    
    def setUp(self):
        print ("setup")
        self.eq = Ideal_Four()
        
    def test_MSE(self):
        """ test method for MSE """
        expected = (33, 0.08056848922483674)
        actual = self.eq.MSE(train.y1)
        
        self.assertEqual(expected, actual)
    
    def test_MSE_ALL(self):
        """ test method for MSE_ALL """
        expected = (41, 0.08621440844128392)
        actual = self.eq.MSE_ALL(train)[1]

        self.assertEqual(expected, actual)
        
    def test_Ideal_Dataset(self):
        """test method for Ideal_Dataset"""
        expected = (20.12461)
        actual = self.eq.Ideal_Dataset(train)[0].iloc[0]
        
        self.assertEqual(expected, actual)
    
    def tearDown(self):
        print ("tearDown")
        del self.eq

In [62]:
if __name__ == '__main__':
    unittest.main(argv = ['first-arg-is-ignored'], exit = False)

.

setup
tearDown

..

setup
tearDown
setup
tearDown

----------------------------------------------------------------------
Ran 3 tests in 0.427s

OK

In [63]:
"""Observe the test datasets."""
test = pd.read_csv('test.csv', index_col = 0)
test

                y
x
 12.6  257.215420
-14.9    0.267808
-4.5     6.118259
 2.4     5.181103
-17.9   -0.845322
...           ...
 7.3    14.125660
-10.0  -25.212278
-19.4   -0.169160
 11.0   22.082275
 10.4  117.566230

[100 rows x 1 columns]

In [64]:
"""There are three rows with the same x value but different y values."""
test.sort_index(ascending = True)

                y
x
-19.4   -0.169160
-19.4  214.276120
-19.4  386.796300
-18.7    0.619703
-18.6    0.302509
...           ...
 18.6   94.105940
 18.8  363.701540
 19.0   74.764200
 19.4   77.410530
 19.7   18.980263

[100 rows x 1 columns]

In [65]:
"""The test data is loaded with the index."""
test = pd.read_csv('test.csv')
test

       x           y
0   12.6  257.215420
1  -14.9    0.267808
2   -4.5    6.118259
3    2.4    5.181103
4  -17.9   -0.845322
..   ...         ...
95   7.3   14.125660
96 -10.0  -25.212278
97 -19.4   -0.169160
98  11.0   22.082275
99  10.4  117.566230

[100 rows x 2 columns]

In [66]:
"""The test datasets have 100 rows."""
len(test)

100

In [67]:
"""Find the best function and the deviation for a point of the test data from the four ideal functions."""
def TEST(train, j):
    Test = []
    for i in range(4):
        dev = Ideal_four[i][Ideal_four[i].index == test.iloc[j, 0]].iloc[0] \
- test.iloc[j, 1]
        Test.append(dev)
        
    Test_min = min(Test, key = abs)
    Test_index = Test.index(Test_min)
    
    return Test_min, Test_index

In [68]:
"""This is the best function and deviation for the first point."""
TEST(train, 0)

(-88.45542, 3)

In [69]:
"""This is the best function and deviation for the second point."""
TEST(train, 1)

(0.45507362, 2)

In [70]:
"""Exception handlings for the TEST function."""
try:
    result = TEST(train, 0)
    print('The best function for the first point in the test data and the deviatoin is:{}'.format(result))
except Exception as e:
    print('Calculation error')
    print(e)
else:
    print('No error')
finally:
    print('End')

The best function for the first point in the test data and the deviatoin is:(-88.45542, 3)
No error
End

In [71]:
"""Exception handlings for the TEST function."""
try:
    result = TEST(train, 0)
    print('The best function for the first point in the test data and the deviatoin is:{}'.format(result))
except TypeError as e:
    print('Wrong type')
    print(e)
except Exception as e:
    print('Calculation error')
    print(e)
else:
    print('No error')
finally:
    print('End')

The best function for the first point in the test data and the deviatoin is:(-88.45542, 3)
No error
End

In [72]:
"""This is the function to find the best function and deviation for every point in the test data."""
def TEST_ALL(train):
    Test_all_min = []
    Test_all_index = []
    for i in range(100):
        Test_min = TEST(train, i)[0]
        Test_index = TEST(train, i)[1]
        Test_all_min.append(Test_min)
        Test_all_index.append(Test_index)
    return Test_all_min, Test_all_index

In [73]:
"""Define the results as Delta and No to reduce information."""
Delta = TEST_ALL(train)[0]
No = TEST_ALL(train)[1]

In [74]:
"""Exception handlings for the TEST_ALL function."""
try:
    result = TEST_ALL(train)[0]
    print('Deviations for every point in the test data are:{}'.format(result))
except TypeError as e:
    print('Wrong type')
    print(e)
except Exception as e:
    print('Calculation error')
    print(e)
else:
    print('No error')
finally:
    print('End')

Deviations for every point in the test data are:[-88.45542, 0.45507362, -1.093321800000001, -0.043371400000000726, 0.032164360000000114, 1.0781770000000002, -43.287900000000036, -0.47358634999999993, 0.976146, -31.743486999999995, -0.9415610000000001, -0.36768049999999874, -0.7910040000000009, 0.8462350000000001, 172.08388, -0.9832679999999989, -0.4429439999999998, 0.1607734999999999, -218.49630000000002, -1.2779364999999996, -0.03623079999999934, -0.12025879999999933, -1.1063115999999997, 0.5728756999999991, -0.39277799999999985, -82.32873000000002, 0.5556340000000048, -36.68926, 0.8797448000000005, -0.024015000000002118, -38.34900000000001, -373.8241, 0.91999537, 0.6574309999999972, 0.388370000000009, -151.51927999999998, -0.5028551300000002, -0.6543209999999977, 0.9329459999999994, -151.59296, 0.22488240000000026, 7.640233999999998, -0.7182670000000009, -13.549469999999992, 0.935570000000002, -1.0670871700000002, 0.4937016000000001, -0.9321639499999999, -0.43629999999996016, -1.1175999999999817, -1.0583760000000026, -1.11655665, 1.19733998, -255.5849, -0.7622350000000004, -57.029430000000005, -146.65323600000002, -1.01302696, 3.7539699999999954, 0.22221400000000102, -1.1975644, -0.76870178, 0.34083672, -0.54948246, 0.27972100000000033, -0.37927489999999997, -0.39721899999999977, -288.21905, -1.2206500000000062, -1.2570660000000018, -219.39507000000003, -183.42557999999997, 4.673569999999998, -0.2851284999999999, 1.04804009, 0.7446899999999914, -0.67385166, -0.3141199999999884, 1.129482000000003, 0.5812100000000129, -43.506840000000004, -1.3669900000000013, -40.278636999999996, 0.12783299999999898, 1.0388340000000014, 0.6169910000000023, -0.26153999999996813, 0.9108685249999999, -0.36798278, 1.2566783000000001, 0.6521290000000004, -1.1228870000000004, 0.1068870000000004, -0.2692260000000033, -0.2249260000000035, 0.899557999999999, 5.484288000000003, 0.69222535, -0.5822690000000001, 0.5937699999999921]
No error
End

In [75]:
"""Exception handlings for the TEST_ALL function."""
try:
    result = TEST_ALL(train)[1]
    print('The best functions for every point in the test data are:{}'.format(result))
except Exception as e:
    print('Calculation error')
    print(e)
else:
    print('No error')
finally:
    print('End')

The best functions for every point in the test data are:[3, 2, 0, 1, 2, 0, 3, 2, 3, 0, 1, 0, 0, 0, 3, 3, 1, 0, 3, 2, 1, 0, 2, 1, 0, 3, 1, 1, 0, 0, 1, 3, 2, 0, 3, 3, 2, 0, 1, 3, 0, 0, 1, 3, 3, 2, 0, 2, 3, 3, 1, 2, 2, 3, 0, 1, 1, 2, 3, 3, 0, 2, 2, 2, 0, 2, 0, 3, 3, 0, 3, 3, 3, 0, 2, 3, 2, 3, 1, 3, 3, 3, 3, 1, 1, 0, 3, 2, 1, 2, 1, 1, 3, 1, 0, 1, 1, 2, 1, 3]
No error
End

In [76]:
Delta

[-88.45542,
 0.45507362,
 -1.093321800000001,
 -0.043371400000000726,
 0.032164360000000114,
 1.0781770000000002,
 -43.287900000000036,
 -0.47358634999999993,
 0.976146,
 -31.743486999999995,
 -0.9415610000000001,
 -0.36768049999999874,
 -0.7910040000000009,
 0.8462350000000001,
 172.08388,
 -0.9832679999999989,
 -0.4429439999999998,
 0.1607734999999999,
 -218.49630000000002,
 -1.2779364999999996,
 -0.03623079999999934,
 -0.12025879999999933,
 -1.1063115999999997,
 0.5728756999999991,
 -0.39277799999999985,
 -82.32873000000002,
 0.5556340000000048,
 -36.68926,
 0.8797448000000005,
 -0.024015000000002118,
 -38.34900000000001,
 -373.8241,
 0.91999537,
 0.6574309999999972,
 0.388370000000009,
 -151.51927999999998,
 -0.5028551300000002,
 -0.6543209999999977,
 0.9329459999999994,
 -151.59296,
 0.22488240000000026,
 7.640233999999998,
 -0.7182670000000009,
 -13.549469999999992,
 0.935570000000002,
 -1.0670871700000002,
 0.4937016000000001,
 -0.9321639499999999,
 -0.43629999999996016,
 -1.1175999999999817,
 -1.0583760000000026,
 -1.11655665,
 1.19733998,
 -255.5849,
 -0.7622350000000004,
 -57.029430000000005,
 -146.65323600000002,
 -1.01302696,
 3.7539699999999954,
 0.22221400000000102,
 -1.1975644,
 -0.76870178,
 0.34083672,
 -0.54948246,
 0.27972100000000033,
 -0.37927489999999997,
 -0.39721899999999977,
 -288.21905,
 -1.2206500000000062,
 -1.2570660000000018,
 -219.39507000000003,
 -183.42557999999997,
 4.673569999999998,
 -0.2851284999999999,
 1.04804009,
 0.7446899999999914,
 -0.67385166,
 -0.3141199999999884,
 1.129482000000003,
 0.5812100000000129,
 -43.506840000000004,
 -1.3669900000000013,
 -40.278636999999996,
 0.12783299999999898,
 1.0388340000000014,
 0.6169910000000023,
 -0.26153999999996813,
 0.9108685249999999,
 -0.36798278,
 1.2566783000000001,
 0.6521290000000004,
 -1.1228870000000004,
 0.1068870000000004,
 -0.2692260000000033,
 -0.2249260000000035,
 0.899557999999999,
 5.484288000000003,
 0.69222535,
 -0.5822690000000001,
 0.5937699999999921]

In [77]:
No

[3,
 2,
 0,
 1,
 2,
 0,
 3,
 2,
 3,
 0,
 1,
 0,
 0,
 0,
 3,
 3,
 1,
 0,
 3,
 2,
 1,
 0,
 2,
 1,
 0,
 3,
 1,
 1,
 0,
 0,
 1,
 3,
 2,
 0,
 3,
 3,
 2,
 0,
 1,
 3,
 0,
 0,
 1,
 3,
 3,
 2,
 0,
 2,
 3,
 3,
 1,
 2,
 2,
 3,
 0,
 1,
 1,
 2,
 3,
 3,
 0,
 2,
 2,
 2,
 0,
 2,
 0,
 3,
 3,
 0,
 3,
 3,
 3,
 0,
 2,
 3,
 2,
 3,
 1,
 3,
 3,
 3,
 3,
 1,
 1,
 0,
 3,
 2,
 1,
 2,
 1,
 1,
 3,
 1,
 0,
 1,
 1,
 2,
 1,
 3]

In [78]:
"""Insert the third column as to deviation in the test data."""
test.insert(2, "Delta Y (test func)", Delta, True)
test

       x           y  Delta Y (test func)
0   12.6  257.215420           -88.455420
1  -14.9    0.267808             0.455074
2   -4.5    6.118259            -1.093322
3    2.4    5.181103            -0.043371
4  -17.9   -0.845322             0.032164
..   ...         ...                  ...
95   7.3   14.125660             0.899558
96 -10.0  -25.212278             5.484288
97 -19.4   -0.169160             0.692225
98  11.0   22.082275            -0.582269
99  10.4  117.566230             0.593770

[100 rows x 3 columns]

In [79]:
"""Insert the fourth column as to the best functions in the test data."""
test.insert(3, "No. of ideal func", No, True)
test

       x           y  Delta Y (test func)  No. of ideal func
0   12.6  257.215420           -88.455420                  3
1  -14.9    0.267808             0.455074                  2
2   -4.5    6.118259            -1.093322                  0
3    2.4    5.181103            -0.043371                  1
4  -17.9   -0.845322             0.032164                  2
..   ...         ...                  ...                ...
95   7.3   14.125660             0.899558                  1
96 -10.0  -25.212278             5.484288                  1
97 -19.4   -0.169160             0.692225                  2
98  11.0   22.082275            -0.582269                  1
99  10.4  117.566230             0.593770                  3

[100 rows x 4 columns]

In [80]:
"""Save the test data in csv for covenience."""
test.to_csv('Table 3-1.csv', header = True, index = False)

In [81]:
Ideal_four

[x
 -20.0    20.124610
 -19.9    20.025234
 -19.8    19.925863
 -19.7    19.826498
 -19.6    19.727139
            ...
  19.5    19.627787
  19.6    19.727139
  19.7    19.826498
  19.8    19.925863
  19.9    20.025234
 Name: y33, Length: 400, dtype: float64,
 x
 -20.0   -40.456474
 -19.9   -40.233820
 -19.8   -40.006836
 -19.7   -39.775787
 -19.6   -39.540980
            ...
  19.5    39.302770
  19.6    39.540980
  19.7    39.775787
  19.8    40.006836
  19.9    40.233820
 Name: y41, Length: 400, dtype: float64,
 x
 -20.0    0.912945
 -19.9    0.867644
 -19.8    0.813674
 -19.7    0.751573
 -19.6    0.681964
            ...
  19.5   -0.605540
  19.6   -0.681964
  19.7   -0.751573
  19.8   -0.813674
  19.9   -0.867644
 Name: y6, Length: 400, dtype: float64,
 x
 -20.0    410.00
 -19.9    406.01
 -19.8    402.04
 -19.7    398.09
 -19.6    394.16
           ...
  19.5    390.25
  19.6    394.16
  19.7    398.09
  19.8    402.04
  19.9    406.01
 Name: y19, Length: 400, dtype: float64]

In [82]:
"""This is the original test datasets."""
test = pd.read_csv('test.csv')
test

       x           y
0   12.6  257.215420
1  -14.9    0.267808
2   -4.5    6.118259
3    2.4    5.181103
4  -17.9   -0.845322
..   ...         ...
95   7.3   14.125660
96 -10.0  -25.212278
97 -19.4   -0.169160
98  11.0   22.082275
99  10.4  117.566230

[100 rows x 2 columns]

In [83]:
"""Create a class to produce Delta and No by combination of the two functions."""
class Delta_No:
    
    def __init__(self, Ideal_four, test):
        self.Ideal_four = Ideal_four
        self.test = test
        
    def TEST(self, train, j):
        Test = []
        for i in range(4):
            dev = self.Ideal_four[i][self.Ideal_four[i].index == self.test.iloc[j, 0]].iloc[0] \
    - self.test.iloc[j, 1]
            Test.append(dev)

        Test_min = min(Test, key = abs)
        Test_index = Test.index(Test_min)

        return Test_min, Test_index
    
    def TEST_ALL(self, train):
        Test_all_min = []
        Test_all_index = []
        for i in range(100):
            Test_min = TEST(train, i)[0]
            Test_index = TEST(train, i)[1]
            Test_all_min.append(Test_min)
            Test_all_index.append(Test_index)
        return Test_all_min, Test_all_index

In [84]:
Delta_No

__main__.Delta_No

In [85]:
Delta_No(Ideal_four, test)

In [86]:
"""The class produces the same results."""
Delta_No(Ideal_four, test).TEST(train, 0)

(-88.45542, 3)

In [87]:
"""The class produces the same results."""
Delta_No(Ideal_four, test).TEST(train, 1)

(0.45507362, 2)

In [88]:
"""The class produces the same results."""
Delta_No(Ideal_four, test).TEST(train, 2)

(-1.093321800000001, 0)

In [89]:
"""The class produces the same results."""
Delta_No(Ideal_four, test).TEST(train, 3)

(-0.043371400000000726, 1)

In [90]:
"""The class produces the same results."""
Delta_No(Ideal_four, test).TEST_ALL(train)

([-88.45542,
  0.45507362,
  -1.093321800000001,
  -0.043371400000000726,
  0.032164360000000114,
  1.0781770000000002,
  -43.287900000000036,
  -0.47358634999999993,
  0.976146,
  -31.743486999999995,
  -0.9415610000000001,
  -0.36768049999999874,
  -0.7910040000000009,
  0.8462350000000001,
  172.08388,
  -0.9832679999999989,
  -0.4429439999999998,
  0.1607734999999999,
  -218.49630000000002,
  -1.2779364999999996,
  -0.03623079999999934,
  -0.12025879999999933,
  -1.1063115999999997,
  0.5728756999999991,
  -0.39277799999999985,
  -82.32873000000002,
  0.5556340000000048,
  -36.68926,
  0.8797448000000005,
  -0.024015000000002118,
  -38.34900000000001,
  -373.8241,
  0.91999537,
  0.6574309999999972,
  0.388370000000009,
  -151.51927999999998,
  -0.5028551300000002,
  -0.6543209999999977,
  0.9329459999999994,
  -151.59296,
  0.22488240000000026,
  7.640233999999998,
  -0.7182670000000009,
  -13.549469999999992,
  0.935570000000002,
  -1.0670871700000002,
  0.4937016000000001,
  -0.9321639499999999,
  -0.43629999999996016,
  -1.1175999999999817,
  -1.0583760000000026,
  -1.11655665,
  1.19733998,
  -255.5849,
  -0.7622350000000004,
  -57.029430000000005,
  -146.65323600000002,
  -1.01302696,
  3.7539699999999954,
  0.22221400000000102,
  -1.1975644,
  -0.76870178,
  0.34083672,
  -0.54948246,
  0.27972100000000033,
  -0.37927489999999997,
  -0.39721899999999977,
  -288.21905,
  -1.2206500000000062,
  -1.2570660000000018,
  -219.39507000000003,
  -183.42557999999997,
  4.673569999999998,
  -0.2851284999999999,
  1.04804009,
  0.7446899999999914,
  -0.67385166,
  -0.3141199999999884,
  1.129482000000003,
  0.5812100000000129,
  -43.506840000000004,
  -1.3669900000000013,
  -40.278636999999996,
  0.12783299999999898,
  1.0388340000000014,
  0.6169910000000023,
  -0.26153999999996813,
  0.9108685249999999,
  -0.36798278,
  1.2566783000000001,
  0.6521290000000004,
  -1.1228870000000004,
  0.1068870000000004,
  -0.2692260000000033,
  -0.2249260000000035,
  0.899557999999999,
  5.484288000000003,
  0.69222535,
  -0.5822690000000001,
  0.5937699999999921],
 [3,
  2,
  0,
  1,
  2,
  0,
  3,
  2,
  3,
  0,
  1,
  0,
  0,
  0,
  3,
  3,
  1,
  0,
  3,
  2,
  1,
  0,
  2,
  1,
  0,
  3,
  1,
  1,
  0,
  0,
  1,
  3,
  2,
  0,
  3,
  3,
  2,
  0,
  1,
  3,
  0,
  0,
  1,
  3,
  3,
  2,
  0,
  2,
  3,
  3,
  1,
  2,
  2,
  3,
  0,
  1,
  1,
  2,
  3,
  3,
  0,
  2,
  2,
  2,
  0,
  2,
  0,
  3,
  3,
  0,
  3,
  3,
  3,
  0,
  2,
  3,
  2,
  3,
  1,
  3,
  3,
  3,
  3,
  1,
  1,
  0,
  3,
  2,
  1,
  2,
  1,
  1,
  3,
  1,
  0,
  1,
  1,
  2,
  1,
  3])

In [91]:
"""The class produces the same results."""
Delta_No(Ideal_four, test).TEST_ALL(train)[0] == Delta

True

In [92]:
"""The class produces the same results."""
Delta_No(Ideal_four, test).TEST_ALL(train)[1] == No

True

In [93]:
"""Peform unittest ofor the class to verify its accuracy."""
import unittest
from unittest import TestCase

class TestDelta_No(unittest.TestCase):
    
    def setUp(self):
        print("setup")
        self.eq = Delta_No(Ideal_four, test)
        
    def test_TEST(self):
        """test method for TEST"""
        expected = (-88.45542, 3)
        actual = self.eq.TEST(train, 0)
        
        self.assertEqual(expected, actual)
        
    def test_TEST_ALL(self):
        """test method for TEST_ALL"""
        expected = Delta
        actual = self.eq.TEST_ALL(train)[0]
        
        self.assertEqual(expected, actual)
        
    def tearDown(self):
        print("tearDown")
        del self.eq

In [94]:
if __name__ == '__main__':
    unittest.main(argv = ['first-arg-is-ignored'], exit = False)

.

setup
tearDown
setup
tearDown

.

setup

...

tearDown
setup
tearDown
setup
tearDown

----------------------------------------------------------------------
Ran 5 tests in 0.629s

OK

In [95]:
"""This is the test datasets with four columns."""
test = pd.read_csv('Table 3-1.csv')
test

       x           y  Delta Y (test func)  No. of ideal func
0   12.6  257.215420           -88.455420                  3
1  -14.9    0.267808             0.455074                  2
2   -4.5    6.118259            -1.093322                  0
3    2.4    5.181103            -0.043371                  1
4  -17.9   -0.845322             0.032164                  2
..   ...         ...                  ...                ...
95   7.3   14.125660             0.899558                  1
96 -10.0  -25.212278             5.484288                  1
97 -19.4   -0.169160             0.692225                  2
98  11.0   22.082275            -0.582269                  1
99  10.4  117.566230             0.593770                  3

[100 rows x 4 columns]

In [96]:
"""This is the x value of the first row of the test datasets."""
test.iloc[0, 0]

12.6

In [97]:
"""This is the corresponding row with the x value in the training datasets."""
train[train.index == test.iloc[0, 0]]

             y1         y2        y3         y4
x
12.6  12.351159  24.856575 -0.382316  168.73499

In [98]:
"""This is the y1 value in the training datasets for the x value."""
train.y1[train.index == test.iloc[0, 0]].iloc[0]

12.351158999999999

In [99]:
"""This is the y33 value in the ideal datasets for the x value."""
Ideal_four[0][Ideal_four[0].index == test.iloc[0, 0]]

x
12.6    12.796875
Name: y33, dtype: float64

In [100]:
"""This is the y33 value in the ideal datasets for the x value."""
Ideal_four[0][train.index == test.iloc[0, 0]].iloc[0]

12.796875

In [101]:
"""Calculate the deviation between train.y1 and ideal.y33 for the x value."""
Ideal_four[0][train.index == test.iloc[0, 0]].iloc[0] \
- train.y1[train.index == test.iloc[0, 0]].iloc[0]

0.4457160000000009

In [102]:
"""Calculate the deviation between train.y1 and ideal.y33 for the x value in the first row in the test data."""
dev1 = Ideal_four[0][train.index == test.iloc[0, 0]].iloc[0] \
- train.y1[train.index == test.iloc[0, 0]].iloc[0]
dev1

0.4457160000000009

In [103]:
"""Calculate the deviation between train.y1 and ideal.y41 for the x value in the first row in the test data."""
dev2 = Ideal_four[1][train.index == test.iloc[0, 0]].iloc[0] \
- train.y2[train.index == test.iloc[0, 0]].iloc[0]
dev2

0.3602370000000015

In [104]:
"""Calculate the deviation between train.y1 and ideal.y6 for the x value in the first row in the test data."""
dev3 = Ideal_four[2][train.index == test.iloc[0, 0]].iloc[0] \
- train.y3[train.index == test.iloc[0, 0]].iloc[0]
dev3

0.348692733

In [105]:
"""Calculate the deviation between train.y1 and ideal.y19 for the x value in the first row in the test data."""
dev4 = Ideal_four[3][train.index == test.iloc[0, 0]].iloc[0] \
- train.y4[train.index == test.iloc[0, 0]].iloc[0]
dev4

0.02501000000000886

In [106]:
"""Find the largest deviation among the four deviations for the x value in the first row in the test data. """
max([dev1, dev2, dev3, dev4], key = abs)

0.4457160000000009

In [107]:
"""This is a function to find the largest deviation for the x value in the second row in the test data."""
def Dev_Max_1(train):
    Dev = []
    for i in range(4):
        dev = Ideal_four[i][train.index == test.iloc[1, 0]].iloc[0] \
    - train["y" + str(i + 1)][train.index == test.iloc[1, 0]].iloc[0]
        Dev.append(dev)
        
    return max(Dev, key = abs)

In [108]:
"""This is the largest deviation for the x value in the second row in the test data."""
Dev_Max_1(train)

-0.4151120000000006

In [109]:
"""This is a function to find the largest deviation for the x value in a row in the test data."""
def Dev_Max(train, j):
    Dev = []
    for i in range(4):
        dev = Ideal_four[i][train.index == test.iloc[j, 0]].iloc[0] \
    - train["y" + str(i + 1)][train.index == test.iloc[j, 0]].iloc[0]
        Dev.append(dev)
        
    return max(Dev, key = abs)

In [110]:
"""The largest deviation for the x value in the first row in the test data."""
Dev_Max(train, 0)

0.4457160000000009

In [111]:
"""The largest deviation for the x value in the second row in the test data."""
Dev_Max(train, 1)

-0.4151120000000006

In [112]:
"""Exception handlings for the Dev_Max function."""
try:
    result = Dev_Max(train, 0)
    print('The largest deviation between the train data and the ideal data with x in the first row in the test data is:{}'.format(result))
except TypeError as e:
    print('Wrong type')
    print(e)
except Exception as e:
    print('Calculation error')
    print(e)
else:
    print('No error')
finally:
    print('End')

The largest deviation between the train data and the ideal data with x in the first row in the test data is:0.4457160000000009
No error
End

In [113]:
"""The test dataset have 100 rows."""
len(test)

100

In [114]:
"""This is a function to find the largest deviations between the train data and ideal data for all the x values in the test data."""
def Dev_Max_ALL(train):
    Dev_all = []
    for i in range(len(test)):
        dev_abmax = Dev_Max(train, i)
        Dev_all.append(dev_abmax)
    return Dev_all

In [115]:
"""Define the results as Dev_ALL to reduce information."""
Dev_ALL = Dev_Max_ALL(train)
Dev_ALL

[0.4457160000000009,
 -0.4151120000000006,
 0.4959270000000001,
 0.3243521400000001,
 0.39629799999999804,
 -0.3550930000000001,
 -0.4612410000000011,
 -0.2691440000000007,
 -0.479357836,
 -0.4259500000000003,
 0.4689770000000024,
 0.4614700000000198,
 -0.4189179999999997,
 -0.3630919999999982,
 -0.2863340000000001,
 0.4804047000000007,
 -0.4113643999999992,
 -0.42501569999999944,
 0.49495199999999784,
 -0.4329699999999974,
 0.3867580999999993,
 -0.4482759999999999,
 -0.41661200000000065,
 0.4483740000000003,
 -0.4516146999999995,
 0.4793520000000001,
 -0.49720400000000353,
 -0.23658999999999253,
 -0.33885147000000004,
 -0.38822741,
 0.3496929999999985,
 -0.38315000000000055,
 0.3991502999999996,
 0.3815098,
 0.49264156000000026,
 0.4617322600000001,
 0.42753999999999337,
 -0.38300999999999874,
 0.44614899999999924,
 -0.26631049999999945,
 -0.3137475999999997,
 0.43006000000002587,
 0.49184999999999945,
 -0.40334849999999994,
 -0.44767699999999877,
 0.2941754999999997,
 -0.4298812000000001,
 -0.4858005499999999,
 -0.2863340000000001,
 -0.40934066,
 -0.43734578999999996,
 -0.32230364999999983,
 -0.4151120000000006,
 -0.45511314,
 0.3659699999999759,
 0.46756999999999493,
 0.4439530000000005,
 0.48537144,
 -0.2788240000000002,
 -0.4132308999999994,
 0.2822500000000048,
 -0.3541939999999997,
 -0.4259500000000003,
 0.26514200000000443,
 0.39245025,
 -0.42887911999999995,
 0.4007668000000001,
 -0.3550576000000003,
 0.30580749999999846,
 0.49724,
 -0.49098799999999976,
 0.4677705000000021,
 -0.45830618599999995,
 -0.49098799999999976,
 -0.31683000000001016,
 0.4649669999999997,
 -0.4501880000000007,
 -0.4009099999999961,
 -0.4453579999999988,
 -0.41842016299999996,
 -0.3518220000000003,
 0.48715100000000255,
 -0.42003200000000085,
 -0.22898196999999998,
 -0.40869299999999953,
 -0.4593779999999974,
 0.3035409999999992,
 0.49495199999999784,
 -0.43146967999999997,
 -0.4127950000000009,
 0.4472529999999999,
 0.4379860000000022,
 -0.3443320000000001,
 -0.49720400000000353,
 0.4439530000000005,
 -0.24706700000000037,
 -0.45830618599999995,
 -0.2863340000000001,
 -0.4174869000000001,
 -0.3811169999999997]

In [116]:
"""Exception handlings for the Dev_Max_ALL function."""
try:
    result = Dev_Max_ALL(train)
    print('The largest deviations between the train data and the ideal data with x in every row in the test data are:{}'.format(result))
except TypeError as e:
    print('Wrong type')
    print(e)
except Exception as e:
    print('Calculation error')
    print(e)
else:
    print('No error')
finally:
    print('End')

The largest deviations between the train data and the ideal data with x in every row in the test data are:[0.4457160000000009, -0.4151120000000006, 0.4959270000000001, 0.3243521400000001, 0.39629799999999804, -0.3550930000000001, -0.4612410000000011, -0.2691440000000007, -0.479357836, -0.4259500000000003, 0.4689770000000024, 0.4614700000000198, -0.4189179999999997, -0.3630919999999982, -0.2863340000000001, 0.4804047000000007, -0.4113643999999992, -0.42501569999999944, 0.49495199999999784, -0.4329699999999974, 0.3867580999999993, -0.4482759999999999, -0.41661200000000065, 0.4483740000000003, -0.4516146999999995, 0.4793520000000001, -0.49720400000000353, -0.23658999999999253, -0.33885147000000004, -0.38822741, 0.3496929999999985, -0.38315000000000055, 0.3991502999999996, 0.3815098, 0.49264156000000026, 0.4617322600000001, 0.42753999999999337, -0.38300999999999874, 0.44614899999999924, -0.26631049999999945, -0.3137475999999997, 0.43006000000002587, 0.49184999999999945, -0.40334849999999994, -0.44767699999999877, 0.2941754999999997, -0.4298812000000001, -0.4858005499999999, -0.2863340000000001, -0.40934066, -0.43734578999999996, -0.32230364999999983, -0.4151120000000006, -0.45511314, 0.3659699999999759, 0.46756999999999493, 0.4439530000000005, 0.48537144, -0.2788240000000002, -0.4132308999999994, 0.2822500000000048, -0.3541939999999997, -0.4259500000000003, 0.26514200000000443, 0.39245025, -0.42887911999999995, 0.4007668000000001, -0.3550576000000003, 0.30580749999999846, 0.49724, -0.49098799999999976, 0.4677705000000021, -0.45830618599999995, -0.49098799999999976, -0.31683000000001016, 0.4649669999999997, -0.4501880000000007, -0.4009099999999961, -0.4453579999999988, -0.41842016299999996, -0.3518220000000003, 0.48715100000000255, -0.42003200000000085, -0.22898196999999998, -0.40869299999999953, -0.4593779999999974, 0.3035409999999992, 0.49495199999999784, -0.43146967999999997, -0.4127950000000009, 0.4472529999999999, 0.4379860000000022, -0.3443320000000001, -0.49720400000000353, 0.4439530000000005, -0.24706700000000037, -0.45830618599999995, -0.2863340000000001, -0.4174869000000001, -0.3811169999999997]
No error
End

In [117]:
"""Insert the information in the fifth colulmn in the test datasets."""
test.insert(4, "Max. of deviation", Dev_ALL, True)
test

,x,y,Delta Y (test func),No. of ideal func,Max. of deviation
0,12.6,257.215420,-88.455420,3,0.445716
1,-14.9,0.267808,0.455074,2,-0.415112
2,-4.5,6.118259,-1.093322,0,0.495927
3,2.4,5.181103,-0.043371,1,0.324352
4,-17.9,-0.845322,0.032164,2,0.396298
...,...,...,...,...,...
95,7.3,14.125660,0.899558,1,-0.247067
96,-10.0,-25.212278,5.484288,1,-0.458306
97,-19.4,-0.169160,0.692225,2,-0.286334
98,11.0,22.082275,-0.582269,1,-0.417487
99,10.4,117.566230,0.593770,3,-0.381117

In [118]:
"""Save it in csv for convenience."""
test.to_csv('Table 3-2.csv', header = True, index = False)

In [119]:
"""Read the test data in the previous version."""
test = pd.read_csv('Table 3-1.csv')
test

       x           y  Delta Y (test func)  No. of ideal func
0   12.6  257.215420           -88.455420                  3
1  -14.9    0.267808             0.455074                  2
2   -4.5    6.118259            -1.093322                  0
3    2.4    5.181103            -0.043371                  1
4  -17.9   -0.845322             0.032164                  2
..   ...         ...                  ...                ...
95   7.3   14.125660             0.899558                  1
96 -10.0  -25.212278             5.484288                  1
97 -19.4   -0.169160             0.692225                  2
98  11.0   22.082275            -0.582269                  1
99  10.4  117.566230             0.593770                  3

[100 rows x 4 columns]

In [120]:
"""Create a class to combine the two functions to find the largest deviations."""
class DEV_MAX_ALL(Delta_No):
    
    def __init__(self, Ideal_four, test):
        super().__init__(Ideal_four, test)
        
    def Dev_Max(self, train, j):
        Dev = []
        for i in range(4):
            dev = self.Ideal_four[i][train.index == self.test.iloc[j, 0]].iloc[0] \
        - train["y" + str(i + 1)][train.index == self.test.iloc[j, 0]].iloc[0]
            Dev.append(dev)

        return max(Dev, key = abs)

    def Dev_Max_ALL(self, train):
        Dev_all = []
        for i in range(len(self.test)):
            dev_abmax = Dev_Max(train, i)
            Dev_all.append(dev_abmax)
        return Dev_all

In [121]:
DEV_MAX_ALL

__main__.DEV_MAX_ALL

In [122]:
DEV_MAX_ALL(Ideal_four, test)

In [123]:
"""This class produces the same results."""
DEV_MAX_ALL(Ideal_four, test).Dev_Max(train, 0)

0.4457160000000009

In [124]:
"""This class produces the same results."""
DEV_MAX_ALL(Ideal_four, test).Dev_Max(train, 1)

-0.4151120000000006

In [125]:
"""This class produces the same results."""
DEV_MAX_ALL(Ideal_four, test).Dev_Max_ALL(train)

[0.4457160000000009,
 -0.4151120000000006,
 0.4959270000000001,
 0.3243521400000001,
 0.39629799999999804,
 -0.3550930000000001,
 -0.4612410000000011,
 -0.2691440000000007,
 -0.479357836,
 -0.4259500000000003,
 0.4689770000000024,
 0.4614700000000198,
 -0.4189179999999997,
 -0.3630919999999982,
 -0.2863340000000001,
 0.4804047000000007,
 -0.4113643999999992,
 -0.42501569999999944,
 0.49495199999999784,
 -0.4329699999999974,
 0.3867580999999993,
 -0.4482759999999999,
 -0.41661200000000065,
 0.4483740000000003,
 -0.4516146999999995,
 0.4793520000000001,
 -0.49720400000000353,
 -0.23658999999999253,
 -0.33885147000000004,
 -0.38822741,
 0.3496929999999985,
 -0.38315000000000055,
 0.3991502999999996,
 0.3815098,
 0.49264156000000026,
 0.4617322600000001,
 0.42753999999999337,
 -0.38300999999999874,
 0.44614899999999924,
 -0.26631049999999945,
 -0.3137475999999997,
 0.43006000000002587,
 0.49184999999999945,
 -0.40334849999999994,
 -0.44767699999999877,
 0.2941754999999997,
 -0.4298812000000001,
 -0.4858005499999999,
 -0.2863340000000001,
 -0.40934066,
 -0.43734578999999996,
 -0.32230364999999983,
 -0.4151120000000006,
 -0.45511314,
 0.3659699999999759,
 0.46756999999999493,
 0.4439530000000005,
 0.48537144,
 -0.2788240000000002,
 -0.4132308999999994,
 0.2822500000000048,
 -0.3541939999999997,
 -0.4259500000000003,
 0.26514200000000443,
 0.39245025,
 -0.42887911999999995,
 0.4007668000000001,
 -0.3550576000000003,
 0.30580749999999846,
 0.49724,
 -0.49098799999999976,
 0.4677705000000021,
 -0.45830618599999995,
 -0.49098799999999976,
 -0.31683000000001016,
 0.4649669999999997,
 -0.4501880000000007,
 -0.4009099999999961,
 -0.4453579999999988,
 -0.41842016299999996,
 -0.3518220000000003,
 0.48715100000000255,
 -0.42003200000000085,
 -0.22898196999999998,
 -0.40869299999999953,
 -0.4593779999999974,
 0.3035409999999992,
 0.49495199999999784,
 -0.43146967999999997,
 -0.4127950000000009,
 0.4472529999999999,
 0.4379860000000022,
 -0.3443320000000001,
 -0.49720400000000353,
 0.4439530000000005,
 -0.24706700000000037,
 -0.45830618599999995,
 -0.2863340000000001,
 -0.4174869000000001,
 -0.3811169999999997]

In [126]:
"""This class produces the same results."""
DEV_MAX_ALL(Ideal_four, test).Dev_Max(train, 0) == Dev_Max(train, 0)

True

In [127]:
"""This class produces the same results."""
DEV_MAX_ALL(Ideal_four, test).Dev_Max_ALL(train) == Dev_ALL

True

In [128]:
"""Perform unittest for the DEV_MAX_ALL function to verify its accuracy."""
import unittest
from unittest import TestCase

class TestDEV_MAX_ALL(unittest.TestCase):
    
    def setUp(self):
        print("setup")
        self.eq = DEV_MAX_ALL(Ideal_four, test)
        
    def test_Dev_Max(self):
        """test method for Dev_Max"""
        expected = (0.4457160000000009)
        actual = self.eq.Dev_Max(train, 0)
        
        self.assertEqual(expected, actual)
        
    def test_Dev_Max_ALL(self):
        """test method for Dev_Max_ALL"""
        expected = Dev_ALL
        actual = self.eq.Dev_Max_ALL(train)
        
        self.assertEqual(expected, actual)
        
    def tearDwon(self):
        print("tearDown")
        del self.eq

In [129]:
"""A minor difference is observed."""
if __name__ == '__main__':
    unittest.main(argv = ['first-arg-is-ignored'], exit = False)

.

setup
setup

..

setup
tearDown
setup

F

tearDown
setup

...

tearDown
setup
tearDown
setup
tearDown

======================================================================
FAIL: test_TEST_ALL (__main__.TestDelta_No)
test method for TEST_ALL
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<ipython-input-93-0bb9f8d57cc5>", line 23, in test_TEST_ALL
    self.assertEqual(expected, actual)
AssertionError: Lists differ: [-88.[161 chars]743486999999995, -0.9415610000000001, -0.36768[1671 chars]9921] != [-88.[161 chars]743487000000002, -0.9415610000000001, -0.36768[1641 chars]9921]

First differing element 9:
-31.743486999999995
-31.743487000000002

Diff is 3102 characters long. Set self.maxDiff to None to see it.

----------------------------------------------------------------------
Ran 7 tests in 0.839s

FAILED (failures=1)

In [130]:
"""Read the test data with the 5 columns."""
test = pd.read_csv('Table 3-2.csv')
test

,x,y,Delta Y (test func),No. of ideal func,Max. of deviation
0,12.6,257.215420,-88.455420,3,0.445716
1,-14.9,0.267808,0.455074,2,-0.415112
2,-4.5,6.118259,-1.093322,0,0.495927
3,2.4,5.181103,-0.043371,1,0.324352
4,-17.9,-0.845322,0.032164,2,0.396298
...,...,...,...,...,...
95,7.3,14.125660,0.899558,1,-0.247067
96,-10.0,-25.212278,5.484288,1,-0.458306
97,-19.4,-0.169160,0.692225,2,-0.286334
98,11.0,22.082275,-0.582269,1,-0.417487
99,10.4,117.566230,0.593770,3,-0.381117

In [131]:
"""Compare deviations between the test data and the training data."""
(test.iloc[:, 2]) ** 2, ((test).iloc[:, 4] ** 2) * 2

(0     7824.361327
 1        0.207092
 2        1.195353
 3        0.001881
 4        0.001035
          ...
 95       0.809205
 96      30.077415
 97       0.479176
 98       0.339037
 99       0.352563
 Name: Delta Y (test func), Length: 100, dtype: float64,
 0     0.397326
 1     0.344636
 2     0.491887
 3     0.210409
 4     0.314104
         ...
 95    0.122084
 96    0.420089
 97    0.163974
 98    0.348591
 99    0.290500
 Name: Max. of deviation, Length: 100, dtype: float64)

In [132]:
"""Remove test data if its daviation from the best ideal function exceeds the max deviation for the training data * sqrt(2)."""
test_final = test[(test.iloc[:, 2]) ** 2 <= ((test).iloc[:, 4] ** 2) * 2]
test_final

,x,y,Delta Y (test func),No. of ideal func,Max. of deviation
1,-14.9,0.267808,0.455074,2,-0.415112
3,2.4,5.181103,-0.043371,1,0.324352
4,-17.9,-0.845322,0.032164,2,0.396298
11,-14.4,14.940257,-0.367680,0,0.461470
16,1.8,4.529868,-0.442944,1,-0.411364
17,-0.9,2.249621,0.160773,0,-0.425016
20,-2.9,-5.883394,-0.036231,1,0.386758
21,-3.9,4.615812,-0.120259,0,-0.448276
23,4.3,7.569041,0.572876,1,0.448374
24,-5.3,6.145169,-0.392778,0,-0.451615
26,-17.2,-34.457184,0.555634,1,-0.497204
29,9.2,9.491855,-0.024015,0,-0.388227
34,14.5,219.861630,0.388370,3,0.492642
36,13.6,-0.356307,-0.502855,2,0.427540
40,0.7,2.118192,0.224882,0,-0.313748
46,0.3,1.762401,0.493702,0,-0.429881
59,6.5,52.027786,0.222214,3,-0.413231
62,-15.2,0.145562,0.340837,2,-0.425950
64,-8.0,8.026902,0.279721,0,0.392450
65,6.4,0.262726,-0.379275,2,-0.428879
66,-17.6,18.138695,-0.397219,0,0.400767
73,6.9,7.538404,-0.285128,0,-0.490988
77,-7.8,71.154120,-0.314120,3,-0.400910
79,-9.8,105.458790,0.581210,3,-0.418420
83,-12.4,-24.845030,0.127833,1,-0.228982
85,-18.5,18.017654,0.616991,0,-0.459378
86,18.8,363.701540,-0.261540,3,0.303541
88,0.2,0.867317,-0.367983,1,-0.431470
92,3.3,20.783113,0.106887,3,-0.344332
93,-17.2,-33.632324,-0.269226,1,-0.497204
94,18.3,18.661032,-0.224926,0,0.443953
98,11.0,22.082275,-0.582269,1,-0.417487

In [133]:
"""Rename the fourth column's values as 'y33', 'y41', 'y6', and 'y19'."""
test_final.iloc[:, 3] = test_final.iloc[:, 3].replace([0, 1, 2, 3], [Ideal_four[0].name, Ideal_four[1].name, Ideal_four[2].name, Ideal_four[3].name])
test_final

C:\Users\gokif\anaconda3\lib\site-packages\pandas\core\indexing.py:1745: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

       x           y  Delta Y (test func) No. of ideal func  Max. of deviation
1  -14.9    0.267808             0.455074                y6          -0.415112
3    2.4    5.181103            -0.043371               y41           0.324352
4  -17.9   -0.845322             0.032164                y6           0.396298
11 -14.4   14.940257            -0.367680               y33           0.461470
16   1.8    4.529868            -0.442944               y41          -0.411364
17  -0.9    2.249621             0.160773               y33          -0.425016
20  -2.9   -5.883394            -0.036231               y41           0.386758
21  -3.9    4.615812            -0.120259               y33          -0.448276
23   4.3    7.569041             0.572876               y41           0.448374
24  -5.3    6.145169            -0.392778               y33          -0.451615
26 -17.2  -34.457184             0.555634               y41          -0.497204
29   9.2    9.491855            -0.024015               y33          -0.388227
34  14.5  219.861630             0.388370               y19           0.492642
36  13.6   -0.356307            -0.502855                y6           0.427540
40   0.7    2.118192             0.224882               y33          -0.313748
46   0.3    1.762401             0.493702               y33          -0.429881
59   6.5   52.027786             0.222214               y19          -0.413231
62 -15.2    0.145562             0.340837                y6          -0.425950
64  -8.0    8.026902             0.279721               y33           0.392450
65   6.4    0.262726            -0.379275                y6          -0.428879
66 -17.6   18.138695            -0.397219               y33           0.400767
73   6.9    7.538404            -0.285128               y33          -0.490988
77  -7.8   71.154120            -0.314120               y19          -0.400910
79  -9.8  105.458790             0.581210               y19          -0.418420
83 -12.4  -24.845030             0.127833               y41          -0.228982
85 -18.5   18.017654             0.616991               y33          -0.459378
86  18.8  363.701540            -0.261540               y19           0.303541
88   0.2    0.867317            -0.367983               y41          -0.431470
92   3.3   20.783113             0.106887               y19          -0.344332
93 -17.2  -33.632324            -0.269226               y41          -0.497204
94  18.3   18.661032            -0.224926               y33           0.443953
98  11.0   22.082275            -0.582269               y41          -0.417487

In [134]:
"""Remove the fifth column."""
test_final = test_final.drop(['Max. of deviation'], axis = 1)
test_final

       x           y  Delta Y (test func) No. of ideal func
1  -14.9    0.267808             0.455074                y6
3    2.4    5.181103            -0.043371               y41
4  -17.9   -0.845322             0.032164                y6
11 -14.4   14.940257            -0.367680               y33
16   1.8    4.529868            -0.442944               y41
17  -0.9    2.249621             0.160773               y33
20  -2.9   -5.883394            -0.036231               y41
21  -3.9    4.615812            -0.120259               y33
23   4.3    7.569041             0.572876               y41
24  -5.3    6.145169            -0.392778               y33
26 -17.2  -34.457184             0.555634               y41
29   9.2    9.491855            -0.024015               y33
34  14.5  219.861630             0.388370               y19
36  13.6   -0.356307            -0.502855                y6
40   0.7    2.118192             0.224882               y33
46   0.3    1.762401             0.493702               y33
59   6.5   52.027786             0.222214               y19
62 -15.2    0.145562             0.340837                y6
64  -8.0    8.026902             0.279721               y33
65   6.4    0.262726            -0.379275                y6
66 -17.6   18.138695            -0.397219               y33
73   6.9    7.538404            -0.285128               y33
77  -7.8   71.154120            -0.314120               y19
79  -9.8  105.458790             0.581210               y19
83 -12.4  -24.845030             0.127833               y41
85 -18.5   18.017654             0.616991               y33
86  18.8  363.701540            -0.261540               y19
88   0.2    0.867317            -0.367983               y41
92   3.3   20.783113             0.106887               y19
93 -17.2  -33.632324            -0.269226               y41
94  18.3   18.661032            -0.224926               y33
98  11.0   22.082275            -0.582269               y41

In [135]:
"""Save the final test data in csv for convenience."""
test_final.to_csv('Table 3-Final.csv', header = True, index = False)